org: joebuntu
app: current
service: current

custom:
  settings:
    AUTHOR_TABLE: curr_Author
    PUBLICATION_TABLE: curr_Publication

layers:
  commonLibs:
    path: layer
    compatibleRuntimes:
      - nodejs10.x

provider:
  name: aws
  runtime: nodejs10.x
  environment: ${self:custom.settings}
  region: us-east-2
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.AUTHOR_TABLE}"
        - "arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.settings.PUBLICATION_TABLE}"

functions:
  createAuthor:
    handler: src/functions/author.create
    layers:
      - {Ref: CommonLibsLambdaLayer}
    events:
      - http:
          path: author
          method: post
  getAllAuthors:
    handler: src/functions/author.getAll
    layers:
      - {Ref: CommonLibsLambdaLayer}
    events:
      - http:
          path: author
          method: get
  getAuthorById:
    handler: src/functions/author.getById
    layers:
      - {Ref: CommonLibsLambdaLayer}
    events:
      - http:
          path: author/{authorId}
          method: get
  updateAuthor:
    handler: src/functions/author.update
    layers:
      - {Ref: CommonLibsLambdaLayer}
    events:
      - http:
          path: author/{authorId}
          method: put
  deleteAuthor:
    handler: src/functions/author.delete
    layers:
      - {Ref: CommonLibsLambdaLayer}
    events:
      - http:
          path: author/{authorId}
          method: delete
  createPublication:
    handler: src/functions/publication.create
    layers:
      - {Ref: CommonLibsLambdaLayer}
    events:
      - http:
          path: publication
          method: post
  getAllPublications:
    handler: src/functions/publication.getAll
    layers:
      - {Ref: CommonLibsLambdaLayer}
    events:
      - http:
          path: publication
          method: get
  getAllOrderedPublications:
    handler: src/functions/publication.getAllOrdered
    layers:
      - {Ref: CommonLibsLambdaLayer}
    events:
      - http:
          path: publication/order/{order}
          method: get
  getPublicationById:
    handler: src/functions/publication.getById
    layers:
      - {Ref: CommonLibsLambdaLayer}
    events:
      - http:
          path: publication/{publicationId}
          method: get
  getPublicationByAuthorId:
    handler: src/functions/publication.getByAuthorId
    layers:
      - {Ref: CommonLibsLambdaLayer}
    events:
      - http:
          path: publication/author/{authorId}
          method: get
  updatePublication:
    handler: src/functions/publication.update
    layers:
      - {Ref: CommonLibsLambdaLayer}
    events:
      - http:
          path: publication/{publicationId}
          method: put
  deletePublication:
    handler: src/functions/publication.delete
    layers:
      - {Ref: CommonLibsLambdaLayer}
    events:
      - http:
          path: publication/{publicationId}
          method: delete

resources:
  Resources:
    AuthorTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "authorId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "authorId"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.AUTHOR_TABLE}
    PublicationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: "publicationId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "publicationId"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.settings.PUBLICATION_TABLE}
